name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'coretto'
        java-version: '11'
        cache: maven

    - name: Install Liquibase
      run: |
        curl -LJO https://github.com/liquibase/liquibase/releases/download/v4.28.0/liquibase-4.28.0.tar.gz
        tar -xzf liquibase-4.28.0.tar.gz
        sudo ln -s $(pwd)/liquibase /usr/local/bin/liquibase

    - name: Run Liquibase Migrations
      run: liquibase update
      env:
        LIQUIBASE_URL: jdbc:postgresql://localhost:5432/testdb
        LIQUIBASE_CHANGELOG_FILE: db/changeLog.xml

    - name: Run Tests
      run: ./mvnw clean test
